name: Executar Scraper de Noticias

on:
  schedule:
    - cron: '0 14 * * 1'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Descargar el codigo del repositorio
        uses: actions/checkout@v4.2.2

      - name: Configurar Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar el scraper
        run: python scraper-noticias.py

      - name: Guardar y subir cambios al repositorio
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add noticias_master.csv
          git diff-index --quiet HEAD || git commit -m "bot: actualizacion automatica de noticias_master.csv"
          git push
